language: objective-c
osx_image: xcode8.2
xcode_workspace: WarmHands.xcworkspace
xcode_scheme: WarmHands
xcode_sdk: iphonesimulator9.2
script:
- xctool -workspace WarmHands.xcworkspace -scheme WarmHands build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
- bash <(curl -s https://codecov.io/bash)
